/**
 * Pattern registry — single source of truth for all patterns.
 * Add new patterns here; the homepage and pattern page read from this.
 */
const PATTERNS = [
  {
    slug: "orchestrator-satellite-communication",
    title: "Orchestrator-Worker Communication",
    summary: "Dispatcher-based task dispatch to ephemeral Claude Code CLI processes with priority kanban queue, worktree isolation, and GitHub CC fallback.",
    status: "published",
  },
  {
    slug: "satellite-permission-escalation",
    title: "Worker Permission Escalation",
    summary: "Static string-based autonomy tiers (AUTO/NOTIFY/ASK/NEVER) per capability for deterministic worker permission routing.",
    status: "published",
  },
  {
    slug: "activity-tracking-architecture",
    title: "Activity Tracking Architecture",
    summary: "Session-based activity tracking with inter-session messaging, per-session tool permissions, and parent-child session hierarchies.",
    status: "published",
  },
  {
    slug: "unified-search-across-kbs",
    title: "Unified Search Across KBs",
    summary: "Architecture for searching multiple project knowledge bases and memory simultaneously.",
    status: "published",
  },
  {
    slug: "multi-model-deliberation",
    title: "Multi-Model Deliberation",
    summary: "Combining multiple AI models for higher-confidence decisions through structured debate.",
    status: "published",
  },
  {
    slug: "scheduled-autonomous-maintenance",
    title: "Scheduled Autonomous Maintenance",
    summary: "Worker task pipeline with multi-step execution, template interpolation, and built-in pipelines for automated project maintenance.",
    status: "published",
  },
  {
    slug: "context-assembly-pipeline",
    title: "Context Assembly Pipeline",
    summary: "Single-pass parallel context assembly with token budgeting across multiple sources.",
    status: "published",
  },
  {
    slug: "capability-manifest-registration",
    title: "Capability Manifest Registration",
    summary: "Dual registration system combining Map-based tool registry with entity/widget type resolution and alias support.",
    status: "published",
  },
  {
    slug: "declarative-capability-system",
    title: "Declarative Capability System",
    summary: "Four-tier capability model (tools, skills, reflexes, workflows) with string-based autonomy tiers (AUTO/NOTIFY/ASK/NEVER).",
    status: "published",
  },
  {
    slug: "evolution-and-self-improvement",
    title: "Evolution and Self-Improvement",
    summary: "Success-driven learning cycle with coactivation tracking, secondary corrections processing, and preference synthesis from operational data.",
    status: "published",
  },
  {
    slug: "unified-event-system",
    title: "Unified Event System",
    summary: "Dual-mode TypeScript event bus with internal entity.invalidated emission, debounced entity events, and immediate system events.",
    status: "published",
  },
  {
    slug: "message-processing-pipeline",
    title: "Message Processing Pipeline",
    summary: "Modular six-stage pipeline with parallel context assembly, planning, deduplicated tool execution, and post-processing.",
    status: "published",
  },
  {
    slug: "error-triage-and-recovery",
    title: "Error Triage and Recovery",
    summary: "Dual-layer error handling where build/test failures are auto-retryable (agents can fix code) and network/permission errors are not (agents cannot fix infrastructure).",
    status: "published",
  },
  {
    slug: "intent-driven-self-scheduling",
    title: "Intent-Driven Self-Scheduling",
    summary: "Cron-based scheduling dispatching through /api/workers/:workerType/dispatch with priority kanban queue integration and agent self-scheduling.",
    status: "published",
  },
  {
    slug: "decision-gating-and-autonomy-tiers",
    title: "Decision Gating and Autonomy Tiers",
    summary: "Dynamic autonomy rules evaluating domain confidence and action fingerprints to route decisions through AUTO/NOTIFY/ASK tiers with autonomy-boost promotion.",
    status: "published",
  },
  {
    slug: "domain-aware-memory-scoring",
    title: "Domain-Aware Memory Scoring",
    summary: "Combined scoring of embedding similarity, recency decay, and access frequency for vector-based memory retrieval.",
    status: "published",
  },
  {
    slug: "plugin-system-and-hot-reload",
    title: "Plugin System and Hot-Reload",
    summary: "Module-based plugin loading via lib/plugins/loader.js with fs.watch hot-reload, lifecycle states, and code-exported capability contributions.",
    status: "published",
  },
  {
    slug: "skill-extraction-and-fast-path-routing",
    title: "Skill Extraction and Fast-Path Routing",
    summary: "File-based YAML skill discovery with frontmatter trigger matching for fast-path dispatch and designed (not yet operational) reflex promotion.",
    status: "published",
  },
  {
    slug: "autonomous-agent-cycle",
    title: "Autonomous Agent Cycle",
    summary: "Queue-based cognitive processor with rule matching on a 5-second tick, paired with a periodic objectives review loop for goal tracking.",
    status: "published",
  },
  {
    slug: "dynamic-system-prompt-composition",
    title: "Dynamic System Prompt Composition",
    summary: "Hardcoded persona and behaviors with capability manifest and anti-patterns appended at dispatch time.",
    status: "published",
  },
  {
    slug: "knowledge-graph-and-relationship-discovery",
    title: "Knowledge Graph and Relationship Discovery",
    summary: "Generic entity relationships stored in the documents table with relationship scoring and multi-hop traversal for context enrichment.",
    status: "published",
  },
  {
    slug: "anticipation-engine",
    title: "Anticipation Engine",
    summary: "Domain-level confidence tracking with asymmetric scoring where successes slowly build confidence and failures rapidly reduce it via 1.25x correction multiplier.",
    status: "published",
  },
  {
    slug: "cognitive-processing-loop",
    title: "Cognitive Processing Loop",
    summary: "Background event-driven processing with rule matching for continuous autonomous awareness.",
    status: "published",
  },
  {
    slug: "unified-trigger-system",
    title: "Unified Trigger System",
    summary: "Plain EventEmitter-style event bus with namespaced events and subscriber management for decoupled inter-module communication.",
    status: "published",
  },
  {
    slug: "channel-adapter-architecture",
    title: "Channel Adapter Architecture",
    summary: "Six-method adapter contract for multi-channel messaging with registry validation and message routing.",
    status: "published",
  },
  {
    slug: "outbound-queue-with-backoff",
    title: "Outbound Queue with Backoff",
    summary: "Async message delivery queue with scheduled delivery, exponential backoff retry, and metadata tracking.",
    status: "published",
  },
  {
    slug: "connector-registry-and-capability-discovery",
    title: "Connector Registry and Capability Discovery",
    summary: "Aspirational pattern for unified service integration with capability discovery. Currently uses direct per-service modules without a shared registry.",
    status: "published",
  },
  {
    slug: "confidence-based-autonomy-gating",
    title: "Confidence-Based Autonomy Gating",
    summary: "Multi-signal weighted confidence scoring with fixed weights and post-calculation adjustments for earned autonomy. Independent from vibe/anticipation system.",
    status: "published",
  },
  {
    slug: "distributed-job-locking",
    title: "Distributed Job Locking",
    summary: "Redis-backed mutex with in-memory fallback, per-job timeout configs, and token-based ownership for preventing concurrent job execution.",
    status: "published",
  },
  {
    slug: "worker-dispatcher-and-priority-queue",
    title: "Worker Dispatcher and Priority Queue",
    summary: "Source-weighted task prioritization with worktree-aware conflict checking and budget tracking for parallel worker dispatch.",
    status: "published",
  },
  {
    slug: "anti-pattern-learning-loop",
    title: "Anti-Pattern Learning Loop",
    summary: "Frequency tracking of recurring protocol errors with automatic injection into the system prompt after configurable occurrence threshold.",
    status: "published",
  },
  {
    slug: "graceful-degradation-and-optional-init",
    title: "Graceful Degradation and Optional Init",
    summary: "Non-blocking startup with per-service .catch() handlers, multi-provider LLM fallback chains, and optional service initialization.",
    status: "published",
  },
  {
    slug: "planning-and-verification-layer",
    title: "Planning and Verification Layer",
    summary: "Pre-execution plan generation with post-execution verification, novel composition detection, and automatic skill generation.",
    status: "published",
  },
  {
    slug: "deliberative-alignment",
    title: "Deliberative Alignment",
    summary: "Standalone multi-model voting module invoked explicitly for high-stakes decisions, not tied to autonomy band thresholds.",
    status: "published",
  },
  {
    slug: "agent-recovery-and-escalation",
    title: "Agent Recovery and Escalation",
    summary: "Strategy-based recovery from tool failures with clarification workflows, batch approval grouping, and action buffering.",
    status: "published",
  },
  {
    slug: "tool-interceptor-and-pre-execution-correction",
    title: "Tool Interceptor and Pre-Execution Correction",
    summary: "Shape-based type inference, parameter validation, and entity normalization applied before tool calls execute for proactive error prevention.",
    status: "published",
  },
  {
    slug: "pipeline-executor-and-workflow-composition",
    title: "Pipeline Executor and Workflow Composition",
    summary: "Operations-based pipeline composition (map, filter, transform, parse, split) with named pipeline storage and sequential execution.",
    status: "published",
  },
  {
    slug: "situation-detection-and-context-awareness",
    title: "Situation Detection and Context Awareness",
    summary: "Runtime situation tracking with detection rules, behavioral modifications, situation stacking, and TTL-based expiry.",
    status: "published",
  },
  {
    slug: "implicit-approval-parsing",
    title: "Implicit Approval Parsing",
    summary: "Natural language approval and denial detection with context-gated activation. Batch and qualified approval parsing designed but not yet implemented.",
    status: "published",
  },
  {
    slug: "widget-sdk-and-declarative-ui",
    title: "Widget SDK and Declarative UI",
    summary: "JSON-based UI primitive system with template binding, layout composition, and runtime widget registration for agent-rendered interfaces.",
    status: "published",
  },
  {
    slug: "undo-and-revert-system",
    title: "Undo and Revert System",
    summary: "Tool-level undo declarations with action log tracking before/after state for time-bounded reversible agent operations.",
    status: "published",
  },
  {
    slug: "embedding-pipeline-and-async-vectorization",
    title: "Embedding Pipeline and Async Vectorization",
    summary: "Non-blocking embedding generation via queue-based batch processing with graceful degradation to keyword search.",
    status: "published",
  },
  {
    slug: "autonomy-boost-and-approval-learning",
    title: "Autonomy Boost and Approval Learning",
    summary: "Time-boxed autonomy boost presets (2h/4h) granting temporary elevated permissions that auto-expire, replacing approval-pattern learning.",
    status: "published",
  },
  {
    slug: "request-scoped-context",
    title: "Request-Scoped Context Propagation",
    summary: "AsyncLocalStorage-based per-request context carrying correlation IDs and embedding caches through async chains. Multi-tenancy hardcoded to tenant 1.",
    status: "published",
  },
  {
    slug: "commitment-tracking",
    title: "Commitment Tracking",
    summary: "Document-based commitment storage with active/overdue querying, progressive three-level escalation, and integration with the cognitive processing loop.",
    status: "published",
  },
  {
    slug: "webhook-event-bridge",
    title: "Webhook Event Bridge",
    summary: "Outbound webhook dispatch with HMAC signing, delivery tracking, and retry. Inbound webhook receiving not yet implemented.",
    status: "published",
  },
  {
    slug: "session-episode-tracking",
    title: "Session Episode Tracking",
    summary: "Episode-based conversation grouping with DB-backed session reconstruction, per-session entity tracking, and topic-drift boundary detection.",
    status: "published",
  },
  {
    slug: "contact-resolution-and-entity-disambiguation",
    title: "Contact Resolution and Entity Disambiguation",
    summary: "Fuzzy cross-platform contact matching with confidence-scored disambiguation, multi-source profile aggregation, and unified entity construction.",
    status: "published",
  },
  {
    slug: "audit-trail-with-pii-sanitization",
    title: "Audit Trail with PII Sanitization",
    summary: "Correlation-ID traced audit logging with batched non-blocking DB persistence and key-based sensitive field redaction before storage.",
    status: "published",
  },
  {
    slug: "declarative-socket-handler-factory",
    title: "Declarative Socket Handler Factory",
    summary: "Factory functions for defining Socket.io handlers declaratively with auto-validation, type coercion, cache invalidation, and broadcast support.",
    status: "published",
  },
  {
    slug: "entity-service-and-universal-crud",
    title: "Entity Service and Universal CRUD",
    summary: "Universal CRUD abstraction for all entity types with type normalization, alias resolution, batch operations, and automatic event emission.",
    status: "published",
  },
  {
    slug: "tools-factory-and-declarative-tool-definition",
    title: "Tools Factory and Declarative Tool Definition",
    summary: "Declarative tool definitions with parameter schemas, automatic validation, entity resolution, error wrapping, and Gemini-compatible declaration generation.",
    status: "published",
  },
  {
    slug: "task-lifecycle-and-state-machine",
    title: "Task Lifecycle and State Machine",
    summary: "Strict state machine for task transitions (todo/in_progress/done/blocked/cancelled) with transient failure auto-retry and progressive backoff.",
    status: "published",
  },
  {
    slug: "task-deduplication",
    title: "Task Deduplication",
    summary: "Keyed deduplication preventing duplicate agent work using compound unique indexes and atomic INSERT ON CONFLICT resolution.",
    status: "published",
  },
  {
    slug: "model-selection-and-llm-fallback",
    title: "Model Selection and LLM Fallback",
    summary: "Primary/fallback LLM provider chain with lazy initialization, concurrent init prevention via mutex flag, and timeout protection.",
    status: "published",
  },
  {
    slug: "graceful-shutdown-ordering",
    title: "Graceful Shutdown Ordering",
    summary: "Ordered SIGINT/SIGTERM teardown sequence with per-phase timeouts and double-signal force exit for safe process termination.",
    status: "published",
  },
  {
    slug: "document-type-system",
    title: "Document Type System",
    summary: "Type-based document handling with property validation, cross-type properties, and bidirectional task-document relationships.",
    status: "published",
  },
  {
    slug: "database-abstraction-and-schema-management",
    title: "Database Abstraction and Schema Management",
    summary: "PostgreSQL abstraction with lazy pool initialization, advisory-lock-protected schema migrations, connection pooling, and dual read/write API.",
    status: "published",
  },
  {
    slug: "redis-optional-caching-and-clustering",
    title: "Redis Optional Caching and Clustering",
    summary: "Optional Redis layer with exponential backoff reconnection, in-memory fallback, Socket.io adapter for multi-instance pub/sub, and health checks.",
    status: "published",
  },
  {
    slug: "rate-limiting-and-api-protection",
    title: "Rate Limiting and API Protection",
    summary: "Sliding-window rate limiter on /api/* routes with per-endpoint configurable limits, custom key extraction, and Redis or in-memory backends.",
    status: "published",
  },
  {
    slug: "structured-logging-with-child-loggers",
    title: "Structured Logging with Child Loggers",
    summary: "Pino-based JSON logging with per-module child loggers, configurable levels, PID/env metadata, and AsyncLocalStorage correlation ID integration.",
    status: "published",
  },
];
