/**
 * Pattern registry — single source of truth for all patterns.
 * Add new patterns here; the homepage and pattern page read from this.
 */
const PATTERNS = [
  {
    slug: "orchestrator-satellite-communication",
    title: "Orchestrator-Satellite Communication",
    summary: "Unix socket protocol with JSONL streaming for real-time orchestrator-to-satellite job dispatch and output streaming.",
    status: "published",
  },
  {
    slug: "satellite-permission-escalation",
    title: "Satellite Permission Escalation",
    summary: "Detecting and recovering from permission-blocked workers in multi-agent dispatch.",
    status: "published",
  },
  {
    slug: "activity-tracking-architecture",
    title: "Activity Tracking Architecture",
    summary: "Three-layer tracking combining JSONL job logs, database session metadata, and in-memory rolling windows.",
    status: "published",
  },
  {
    slug: "unified-search-across-kbs",
    title: "Unified Search Across KBs",
    summary: "Architecture for searching multiple project knowledge bases and memory simultaneously.",
    status: "published",
  },
  {
    slug: "multi-model-deliberation",
    title: "Multi-Model Deliberation",
    summary: "Combining multiple AI models for higher-confidence decisions through structured debate.",
    status: "published",
  },
  {
    slug: "scheduled-autonomous-maintenance",
    title: "Scheduled Autonomous Maintenance",
    summary: "Cron-scheduled autonomous tasks with API-driven management and concurrent execution guards.",
    status: "published",
  },
  {
    slug: "context-assembly-pipeline",
    title: "Context Assembly Pipeline",
    summary: "Single-pass parallel context assembly with token budgeting across multiple sources.",
    status: "published",
  },
  {
    slug: "capability-manifest-registration",
    title: "Capability Manifest Registration",
    summary: "Dual registration system combining Map-based tool registry with entity/widget type resolution and alias support.",
    status: "published",
  },
  {
    slug: "declarative-capability-system",
    title: "Declarative Capability System",
    summary: "Four-tier capability model (tools, skills, reflexes, workflows) with string-based autonomy tiers (AUTO/NOTIFY/ASK/NEVER).",
    status: "published",
  },
  {
    slug: "evolution-and-self-improvement",
    title: "Evolution and Self-Improvement",
    summary: "Corrections-driven learning cycle with coactivation tracking, anti-pattern extraction, and preference synthesis.",
    status: "published",
  },
  {
    slug: "unified-event-system",
    title: "Unified Event System",
    summary: "Dual-mode event bus with debounced entity events and immediate system events for reactive UI.",
    status: "published",
  },
  {
    slug: "message-processing-pipeline",
    title: "Message Processing Pipeline",
    summary: "Modular seven-stage pipeline with parallel context assembly, planning, deduplicated tool execution, and response verification.",
    status: "published",
  },
  {
    slug: "error-triage-and-recovery",
    title: "Error Triage and Recovery",
    summary: "Dual-layer error handling with pattern-based retryability classification and three-category learning triage.",
    status: "published",
  },
  {
    slug: "intent-driven-self-scheduling",
    title: "Intent-Driven Self-Scheduling",
    summary: "Agents create and manage scheduled tasks via API with cron dispatch through a priority kanban queue.",
    status: "published",
  },
  {
    slug: "inner-monologue-and-reflection",
    title: "Inner Monologue and Reflection",
    summary: "Private reflection cycle where an agent thinks without broadcasting, deciding what to surface and what to resolve internally.",
    status: "published",
  },
  {
    slug: "decision-gating-and-autonomy-tiers",
    title: "Decision Gating and Autonomy Tiers",
    summary: "Route autonomous agent decisions through notification tiers to prevent alert fatigue while ensuring critical actions reach humans.",
    status: "published",
  },
  {
    slug: "narrative-memory-generation",
    title: "Narrative Memory Generation",
    summary: "Convert structured operational data into story-form memories with semantic valence for richer retrieval and learning.",
    status: "published",
  },
  {
    slug: "domain-aware-memory-scoring",
    title: "Domain-Aware Memory Scoring",
    summary: "Combined scoring of embedding similarity, recency decay, and access frequency for vector-based memory retrieval.",
    status: "published",
  },
  {
    slug: "plugin-system-and-hot-reload",
    title: "Plugin System and Hot-Reload",
    summary: "Extensible plugin architecture with file watching, context building, and graceful lifecycle management.",
    status: "published",
  },
  {
    slug: "skill-extraction-and-fast-path-routing",
    title: "Skill Extraction and Fast-Path Routing",
    summary: "Embeddings-based semantic skill matching with learned reflex promotion for progressively faster dispatch.",
    status: "published",
  },
  {
    slug: "autonomous-agent-cycle",
    title: "Autonomous Agent Cycle",
    summary: "Event-driven cognitive tick system with adaptive backpressure, priority-based event processing, and DB-backed outbound queue.",
    status: "published",
  },
  {
    slug: "dynamic-system-prompt-composition",
    title: "Dynamic System Prompt Composition",
    summary: "Runtime assembly of system prompts from persona, capabilities, behavioral rules, and contextual signals.",
    status: "published",
  },
  {
    slug: "knowledge-graph-and-relationship-discovery",
    title: "Knowledge Graph and Relationship Discovery",
    summary: "Entity extraction, relationship scoring, and multi-hop graph traversal for enriching agent context.",
    status: "published",
  },
  {
    slug: "anticipation-engine",
    title: "Anticipation Engine",
    summary: "Reactive vibe subsystem that tracks action outcomes, auto-resolves follow-ups, and adjusts domain confidence.",
    status: "published",
  },
  {
    slug: "cognitive-processing-loop",
    title: "Cognitive Processing Loop",
    summary: "Background event-driven processing with rule matching for continuous autonomous awareness.",
    status: "published",
  },
  {
    slug: "unified-trigger-system",
    title: "Unified Trigger System",
    summary: "Polymorphic trigger registry unifying notifications, tool calls, job dispatch, and approval workflows.",
    status: "published",
  },
  {
    slug: "channel-adapter-architecture",
    title: "Channel Adapter Architecture",
    summary: "Pluggable adapter contract for multi-channel messaging with registry validation and message routing.",
    status: "published",
  },
  {
    slug: "outbound-queue-with-backoff",
    title: "Outbound Queue with Backoff",
    summary: "Async message delivery queue with scheduled delivery, exponential backoff retry, and metadata tracking.",
    status: "published",
  },
  {
    slug: "connector-registry-and-capability-discovery",
    title: "Connector Registry and Capability Discovery",
    summary: "Generic connector pattern for external services with type registry, instance caching, and priority-based capability resolution.",
    status: "published",
  },
  {
    slug: "confidence-based-autonomy-gating",
    title: "Confidence-Based Autonomy Gating",
    summary: "Domain-level confidence tracking with asymmetric scoring and configurable correction multipliers for earned autonomy.",
    status: "published",
  },
  {
    slug: "distributed-job-locking",
    title: "Distributed Job Locking",
    summary: "Redis-backed mutex with in-memory fallback, per-job timeout configs, and token-based ownership for preventing concurrent job execution.",
    status: "published",
  },
  {
    slug: "worker-dispatcher-and-priority-queue",
    title: "Worker Dispatcher and Priority Queue",
    summary: "Weighted work source prioritization with repo-level locking and budget tracking for satellite worker dispatch.",
    status: "published",
  },
  {
    slug: "anti-pattern-learning-loop",
    title: "Anti-Pattern Learning Loop",
    summary: "Frequency tracking of recurring protocol errors with automatic injection into the system prompt after configurable occurrence threshold.",
    status: "published",
  },
  {
    slug: "graceful-degradation-and-optional-init",
    title: "Graceful Degradation and Optional Init",
    summary: "Non-blocking startup with Promise.allSettled(), multi-provider LLM fallback chains, and optional service initialization.",
    status: "published",
  },
];
